### ISSUE TITLE
Countdown when starting a game

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot-Plugin-Blackjack#1]
It would be great to have a countdown that counts down to the start of a game. Sometimes, I'm just a fraction of a second too late.

**Comment by Agadar** [comment]
Won't you still be too late even if there's a countdown?

I think a countdown that's updated every few seconds in the 'game starting' message would be a nice addition regardless.

**Comment by Agadar** [comment]
Since it's currently not possible to edit an existing chat message due to limitations of the danktimesbot plugin architecture, and I don't want the bot to spam countdown numbers in individual chat messages, I've opted to simply have the bot announce the number of seconds before the game starts in its opening message (7cef4f34b98a5304342dfc72a02b8f0005e07641).
